# Day 1: Installing and Creating Array

In [7]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.



# import numpy

In [1]:
import numpy as np

# creating array

In [9]:
a = np.array([1,2,3])

In [10]:
b = np.array([[1,2],[3,4]])

In [11]:
c = np.array([[3,4,5],[5,6,7],[7,8,9]])

In [12]:
print(a.shape)

(3,)


In [13]:
print(a.ndim)

1


In [14]:
print(b.shape)

(2, 2)


In [15]:
print(b.ndim)

2


In [16]:
print(c)

[[3 4 5]
 [5 6 7]
 [7 8 9]]


In [17]:
print(c.shape)

(3, 3)


In [18]:
print(c.ndim)

2


# array type

In [19]:
print(type(a))

<class 'numpy.ndarray'>


In [20]:
my_list = ([1,2],[3,4])

In [21]:
my_array = np.array(my_list)

In [22]:
print(my_array)

[[1 2]
 [3 4]]


In [23]:
print(my_array.shape)

(2, 2)


In [24]:
print(my_array.ndim)

2


In [25]:
print(type(my_array))

<class 'numpy.ndarray'>


# Day 2: Indexing and Slicing Array

# indexing in 1D array  

In [26]:
a = np.array([1,2,3,4,5])

In [27]:
print(a[0])

1


In [28]:
print(a[3])

4


In [29]:
print(a[-1])

5


# indexing in 2D array

In [30]:
b = np.array([[10,20,30],[40,50,60]])

In [31]:
print(b[0,0])

10


In [32]:
print(b[0,1])

20


In [33]:
print(b[1,2])

60


# creating 3D array

In [34]:
c = np.array([[[1,2],[3,4]],
              [[5,6],[7,8]]])

In [35]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
print(c[0,1,1])

4


In [37]:
print(c[1,1,0])

7


In [38]:
print(c[1,0,0])

5


# slicing in 1D array

In [39]:
a = np.array([10,20,30,40,50])

In [40]:
print(a[1:4])

[20 30 40]


In [41]:
print(a[:3])

[10 20 30]


In [42]:
print(a[::2]) #every second element

[10 30 50]


# slicing in 2D array

In [79]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [86]:
print(b[0:2,1:2])

[[2]
 [5]]


In [45]:
print(b[0:2,1:]) # Rows 0–1, Columns 1–2

[[2 3]
 [5 6]]


# 📘 NumPy Day 3: Array Operations & Broadcasting

In [44]:
# NumPy is powerful because it allows fast, element-wise operations and broadcasting without writing loops.

# 1. Basic Arithmetic Operations

 NumPy automatically applies operations element-wise:

In [46]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [47]:
print(a+b)

[5 7 9]


In [48]:
print(a-b)

[-3 -3 -3]


In [49]:
print(a*b)

[ 4 10 18]


In [50]:
print(a/b)

[0.25 0.4  0.5 ]


# 2. Array with scalars

 You can perform operations between arrays and single numbers:

In [51]:
print(a+5)

[6 7 8]


In [52]:
print(a*5)

[ 5 10 15]


# 3. Broadcasting

 Broadcasting is NumPy’s way of handling different shapes in operations.

In [54]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([10,20,30])

In [55]:
print(A+B)

[[11 22 33]
 [14 25 36]]


In [ ]:
# Here, B is automatically stretched to match A’s shape.


# 4. Mathematical Function

 NumPy has many built-in functions:

In [56]:
arr = np.array([1,4,9,16])

In [57]:
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sum(arr))
print(np.mean(arr))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[0.         1.38629436 2.19722458 2.77258872]
30
7.5


# 5. Comparison Operators

In [58]:
a = np.array([1,2,3])
b = np.array([2,2,2])

In [59]:
print(a>b)
print(a<b)
print(a==b)

[False False  True]
[ True False False]
[False  True False]


# 📘 NumPy Day 4: Reshaping, Flattening, Stacking & Splitting


# 🔷 1. Reshaping Arrays



Reshaping changes the arrangement of data without changing the data itself.

In [6]:
np = np.array([1,2,3,4,5,6])

In [7]:
reshaped = np.reshape([2,3])

In [8]:
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
# (2, 3) means 2 rows and 3 columns
# The total number of elements must remain the same

# 🔷 2. Flattening Arrays


Flattening converts any array into a 1D array.

In [64]:
flat = reshaped.flatten()
print(flat)

[1 2 3 4 5 6]


# 🔷 3. Stacking Arrays

Vertical Stack (rows on top of each other):

In [70]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [71]:
vstacked = np.vstack((a,b))
print(vstacked)

[[1 2]
 [3 4]
 [5 6]]


Horizontal Stack (columns side by side):

In [94]:
hstacked = np.hstack((a,b.T))
print(hstacked)

[[1 2 5]
 [3 4 6]]


In [93]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])   # Now b is 2D (1 row, 2 columns)

hstacked = np.hstack((a, b.T))
print(hstacked)
# [[1 2 5]
#  [3 4 6]]


[[1 2 5]
 [3 4 6]]


# 🔷 4. Splitting Arrays

Split into equal parts:

In [75]:
arr = np.array([1,2,3,4,5,6])
parts = np.split(arr,3)
print(parts)

[array([1, 2]), array([3, 4]), array([5, 6])]


Split by axis:

In [99]:
matrix = np.array([[1,2,3],[4,5,6]])
split = np.hsplit(matrix,3)
print(split)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


task 1

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [11]:
reshaped = arr.reshape([3,4]) #reshaping

In [10]:
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
flat = reshaped.flatten() #flattened

In [15]:
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


task2

In [19]:
arr1 = np.array([1,2])
arr2 = np.array([3,4])

In [26]:
vstacked = np.vstack((arr1,arr2))  #vertical stack
print(vstacked)

[[1 2]
 [3 4]]


In [27]:
hstacked = np.hstack((arr1,arr2.T))  #horizontal stack
print(hstacked)

[1 2 3 4]


In [29]:
split = np.split(arr,2) #splitting array
print(split)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12])]


# 📘 NumPy Day 5: Random Module

NumPy has a built-in random module (numpy.random) that’s super useful for:

Simulations

Testing algorithms

Generating sample datasets

Machine learning (initial weights, shuffling data)

# 1. Random Integers

In [30]:
import numpy as np

 Single random integer between 0 and 9

In [31]:
print(np.random.randint(10))

5


Array of 5 random integers between 0 and 100

In [32]:
print(np.random.randint(1,100,size=5))

[59 92  7 87 77]


2D array of random integers

In [33]:
print(np.random.randint(1,10,size=(3,3)))

[[5 5 2]
 [8 2 7]
 [8 5 8]]


# 2. Random Floats

Random floats between 0 and 1

In [192]:
print(np.random.rand()) # Single value

0.6807054515547668


In [193]:
print(np.random.rand(3,3)) # 3x3 matrix 

[[0.53093458 0.44778316 0.55289309]
 [0.59269672 0.08085333 0.36965446]
 [0.24215994 0.80313976 0.47030063]]


Random floats from normal distribution

In [194]:
print(np.random.randn(3,3)) # mean=0, std=1

[[-1.42647888 -0.04540266  0.21693673]
 [ 0.51242373  0.54348869  0.02809946]
 [-1.19708706  0.7896728   0.43148946]]


# 3. Random Choice 

Pick random values from a list/array:

In [112]:
arr = np.array([10,20,30,40,50])

In [113]:
print(np.random.choice(arr)) # Single random element

40


In [114]:
print(np.random.choice(arr,2)) # Random 2 elements

[10 50]


In [115]:
print(np.random.choice(arr,2,replace=False)) # No Repeats

[40 10]


# 4. Permutation & Suffling

Shuffle in place

In [93]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr) #shuffled array

[5 1 4 3 2]


Permutation (returns a shuffled copy)

In [81]:
print(np.random.permutation(arr))

[4 5 2 1 3]


# 5. Setting a Random Seed

For reproducibility (getting the same random numbers every time):

In [92]:
np.random.seed(42)
print(np.random.randint(0,10,size=5))
## Always gives the same output: [6 3 7 4 6]

[6 3 7 4 6]


Task 1

In [188]:
# Generate a 3x3 matrix of random integers between 1 and 50 & Find Min and Max values
arr = np.random.randint(1,50,size=(3,3))
print(arr)
print(np.min(arr))
print(np.max(arr))


[[33 42 44]
 [24 15 32]
 [32 24 41]]
15
44


Task 2

In [189]:
# Create an array of 10 random numbers between 10 and 100 & Sort them
arr = np.array([60,20,80,10,40,30,90,100,50,70])
arr.sort()
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


Task 3

Take a list [‘apple’, ‘banana’, ‘cherry’, ‘date’]
Pick 2 random fruits without replacement

In [174]:
import numpy as np

In [175]:
fruits = ["apple", "banana", "cherry", "date"]

In [180]:
select = np.random.choice(fruits,2,replace=False)
print(select)

['banana' 'date']
