# 📘Chapter 6 – Mathematical & Statistical Functions in NumPy

# 1. Basic Mathematical Operations

In [17]:
import numpy as np

In [18]:
a = np.array([2,4,6,8])

In [19]:
b = np.array([1,3,5,7])

In [20]:
print("Addition:", np.add(a, b))

Addition: [ 3  7 11 15]


In [21]:
print("Subtraction:", np.subtract(a,b))

Subtraction: [1 1 1 1]


In [22]:
print("Multiplication:", np.multiply(a,b))

Multiplication: [ 2 12 30 56]


In [23]:
print("Division:", np.divide(a,b))

Division: [2.         1.33333333 1.2        1.14285714]


In [24]:
print("Power:", np.power(a,2))

Power: [ 4 16 36 64]


In [25]:
print("Power:", np.power(b,2))

Power: [ 1  9 25 49]


In [26]:
print("Square Root:", np.sqrt(a))

Square Root: [1.41421356 2.         2.44948974 2.82842712]


# 2. Exponential & Logarithmic Functions

In [27]:
x = np.array([1,2,3,4])

In [28]:
print("Exponentials:", np.exp(x))

Exponentials: [ 2.71828183  7.3890561  20.08553692 54.59815003]


In [29]:
print("Logarithm:", np.log(x))

Logarithm: [0.         0.69314718 1.09861229 1.38629436]


# 3. Trigonometric Functions

In [30]:
angles = np.array([0, np.pi/2, np.pi])

In [31]:
print("Sine:", np.sin(angles))

Sine: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [32]:
print("Cosine:", np.cos(angles))

Cosine: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [33]:
print("Tangent:",np.tan(angles))

Tangent: [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


# 4. Aggregate Functions

In [34]:
arr = np.array([10,20,30,40,50])

In [35]:
print("Sum:", np.sum(arr))

Sum: 150


In [36]:
print("Product:", np.prod(arr))

Product: 12000000


In [37]:
print("Mean:", np.mean(arr))

Mean: 30.0


In [38]:
print("Median:",np.median(arr))

Median: 30.0


In [39]:
print("Variance:", np.var(arr))

Variance: 200.0


In [40]:
print("Standard Deviation:", np.std(arr))

Standard Deviation: 14.142135623730951


# 5. Minimum & Maximum

In [41]:
arr = np.array([15,8,22,4,19])

In [42]:
print("Min:",np.min(arr))

Min: 4


In [43]:
print("Max:", np.max(arr))

Max: 22


In [44]:
print("Index of Min:", np.argmin(arr))

Index of Min: 3


In [45]:
print("Index of Max:", np.argmax(arr))

Index of Max: 2


# 6. Rounding Functions

In [46]:
arr = np.array([3.7,2.3,-1.8,5.5])

In [47]:
print("Round:", np.round(arr))

Round: [ 4.  2. -2.  6.]


In [48]:
print("Floor:", np.floor(arr))

Floor: [ 3.  2. -2.  5.]


In [49]:
print("Ceil:", np.ceil(arr))

Ceil: [ 4.  3. -1.  6.]


# 🔹Real World Example'
# Suppose you have students’ marks and want to calculate class performance:

In [50]:
marks = np.array([56,78,89,45,92,67])

In [51]:
print("Class Average:", np.mean(marks))

Class Average: 71.16666666666667


In [52]:
print("Best Score:", np.max(marks))

Best Score: 92


In [53]:
print("Lowest Score:", np.min(marks))

Lowest Score: 45


In [54]:
print("Score Variance:", np.var(marks))

Score Variance: 288.47222222222223


In [55]:
print(np.max([1,12,33,54,9]))
print(np.min([25,65,3,99,5])) # Other way to find min & max:

54
3


# 📘 Chapter 7: Statistical Functions in NumPy

NumPy provides built-in functions to quickly compute statistics like mean, median, standard deviation, variance, etc. These are very useful in data analysis and machine learning.

# 1. Mean, Median, Mode

In [56]:
import numpy as np

In [57]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [58]:
# Mean
print("Mean:", np.mean(arr))

Mean: 5.0


In [59]:
# Median
print("Median:", np.mean(arr))

Median: 5.0


In [60]:
from scipy import stats

In [61]:
mode_result = stats.mode(arr, keepdims = True)
print("Mode:", mode_result.mode[0])

Mode: 1


# 2. Standard Deviation & Variance

In [62]:
# Standard Deviation (spread of data)
print("Standard Deviation:", np.std(arr))

Standard Deviation: 2.581988897471611


In [63]:
# Variance (square of std deviation)
print("Variance:", np.var(arr))

Variance: 6.666666666666667


# 3. Min, Max, Percentile

In [64]:
# Minimum & Maximum
print("Min:", np.min(arr))
print("Max:", np.max(arr))

Min: 1
Max: 9


In [65]:
# Percentile
print("25th Percentile:", np.percentile(arr, 25))
print("50th Percentile:", np.percentile(arr, 50))
print("75th Percentile:", np.percentile(arr, 75))

25th Percentile: 3.0
50th Percentile: 5.0
75th Percentile: 7.0


# 4. Summation & Cumulative Sum

In [66]:
# Sum of all elements
print("Sum:", np.sum(arr))

Sum: 45


In [67]:
# Cumulative sum (running total)
print("Cumulative Sum:", np.cumsum(arr))

Cumulative Sum: [ 1  3  6 10 15 21 28 36 45]


# 📘 Chapter 8: Linear Algebra in NumPy

The numpy.linalg module provides a collection of linear algebra routines (matrix operations). These are widely used in machine learning, data science, and scientific computing.

# 1. Matrix Multiplication

In [68]:
import numpy as np

In [69]:
# Define two matrices
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [70]:
# Matrix Multiplication
print("Matrix Multiplication:\n", np.dot(A, B))

Matrix Multiplication:
 [[19 22]
 [43 50]]


# 2. Transpose & Determinant

In [71]:
# Transpose
print("Transpose of A:\n", A.T)
print("Transpose of B:\n", B.T)

Transpose of A:
 [[1 3]
 [2 4]]
Transpose of B:
 [[5 7]
 [6 8]]


In [72]:
# Determinant
print("Determinant of A:", np.linalg.det(A))
print("Determinant of B:", np.linalg.det(B))

Determinant of A: -2.0000000000000004
Determinant of B: -1.999999999999999


# 3. Inverse & Rank

In [73]:
# Inverse of Matrix
print("Inverse of Matrix:\n", np.linalg.inv(A))
print("Inverse of Matrix:\n", np.linalg.inv(B))

Inverse of Matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Inverse of Matrix:
 [[-4.   3. ]
 [ 3.5 -2.5]]


In [74]:
# Rank of a Matrix
print("Rank of A:\n", np.linalg.matrix_rank(A))
print("Rank of B:\n", np.linalg.matrix_rank(B))

Rank of A:
 2
Rank of B:
 2


# 4. Eigenvalues & Eigenvectors

In [75]:
import numpy as np

In [76]:
A = np.array([[1,2], [3,4]])

In [77]:
# Eigenvalues & Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [78]:
eigenvalues, eigenvectors = np.linalg.eig(B)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)

Eigenvalues: [-0.15206735 13.15206735]
Eigenvectors: [[-0.75868086 -0.59276441]
 [ 0.65146248 -0.80537591]]


# 5. Solving Linear Equations

Example: Solve system of equations
  2x+y=5x−y=1

In [79]:
# # Coefficient matrix
coeff = np.array([[2,1],[1,-1]])

In [80]:
# Constants
const = np.array([5,1])

In [81]:
# Solve Ax = b
solution = np.linalg.solve(coeff,const)
print("Solution of equations:", solution)

Solution of equations: [2. 1.]


# Chapter 9: Numpy with Real Data

# 1. Loading data from CSV

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [6]:
data = np.genfromtxt("C:/Users/mugee/OneDrive/Desktop/Sales.csv",dtype=None, encoding="utf-8")

In [7]:
print(data.shape)

(6,)


In [8]:
print(data[:5])

['Date,Product,Price,Quantity' '01-01-2025,Laptop,50000,2'
 '02-01-2025,Phone,20000,3' '03-01-2025,Tablet,30000,1'
 '04-01-2025,Headphones,5000,5']


# 2. Working on specific column

In [23]:
price = data[:,2].astype(float)

In [24]:
print("First 3 sales values:\n", data[:3])

First 3 sales values:
 [['01-01-2025' 'Laptop' '50000' '2']
 ['02-01-2025' 'Phone' '20000' '3']
 ['03-01-2025' 'Tablet' '30000' '1']]


# 3. Perform Statistic on a column 

In [29]:
import numpy as np

In [30]:
# Example data (like your screenshot)
data = np.array([
    ["01-01-2025", "Laptop", "50000", "2"],
    ["02-01-2025", "Phone", "20000", "3"],
    ["03-01-2025", "Tablet", "30000", "1"]
])

In [31]:
# Convert columns to numeric
prices = data[:, 2].astype(float)      # Price column
quantities = data[:, 3].astype(float)  # Quantity column

In [32]:
# Statistics
print("Price Mean:", np.mean(prices))
print("Price Median:", np.median(prices))
print("Price Std Dev:", np.std(prices))

Price Mean: 33333.333333333336
Price Median: 30000.0
Price Std Dev: 12472.191289246472


In [33]:
print("Quantity Mean:", np.mean(quantities))
print("Quantity Median:", np.median(quantities))
print("Quantity Std Dev:", np.std(quantities))

Quantity Mean: 2.0
Quantity Median: 2.0
Quantity Std Dev: 0.816496580927726


# 4.Filter data (Boolean Indexing)

In [38]:
# Find sales greater than 5000
high_sales = price[price>5000]
print("High sales", high_sales[:5])

High sales [50000. 20000. 30000.]


# 5. Save processed results back to CSV

In [43]:
np.savetxt("Processed_sales.csv",data, delimiter=",", header="sales", comments="", fmt="%s")

In [44]:
print("Processed sales saved to processed_sales.csv")

Processed sales saved to processed_sales.csv


# Chapter 10: Load Data from Files

# 1. Load CSV file (numeric only)

In [49]:
import numpy as np

In [56]:
sales_data = np.loadtxt("processed_sales.csv", delimiter=",",skiprows=1,dtype=str)

In [51]:
print("Loaded Data:\n", sales_data)

Loaded Data:
 [['01-01-2025' 'Laptop' '50000' '2']
 ['02-01-2025' 'Phone' '20000' '3']
 ['03-01-2025' 'Tablet' '30000' '1']]


# 2. Load mixed data

In [53]:
sales_data = np.genfromtxt("Processed_sales.csv", delimiter=",", dtype=str, skip_header=1)

In [54]:
print("Loaded data from genfromtxt:\n", sales_data)

Loaded data from genfromtxt:
 [['01-01-2025' 'Laptop' '50000' '2']
 ['02-01-2025' 'Phone' '20000' '3']
 ['03-01-2025' 'Tablet' '30000' '1']]


# 3. Check Shape & Type 

In [58]:
print("Shape:",sales_data.shape)

Shape: (3, 4)


In [60]:
print("Data Type:",sales_data.dtype)

Data Type: <U10
